// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDablGz5U38nZi-dipLyabGzHhhaE59Cx0',
    appId: '1:961998777091:web:1a8d9d106b0136c9199736',
    messagingSenderId: '961998777091',
    projectId: 'yagsa-9ce79',
    authDomain: 'yagsa-9ce79.firebaseapp.com',
    storageBucket: 'yagsa-9ce79.firebasestorage.app',
    measurementId: 'G-5DY0C6WNV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX862gcEN5OjZaUF5a3tDoDRxWZrt7nxI',
    appId: '1:961998777091:android:5024194fcb6a2d67199736',
    messagingSenderId: '961998777091',
    projectId: 'yagsa-9ce79',
    storageBucket: 'yagsa-9ce79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtm7XOmEJaLhZHEN9mhE8rYngocu5gEk',
    appId: '1:961998777091:ios:eb9169114e3807be199736',
    messagingSenderId: '961998777091',
    projectId: 'yagsa-9ce79',
    storageBucket: 'yagsa-9ce79.firebasestorage.app',
    iosBundleId: 'com.example.yagsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtm7XOmEJaLhZHEN9mhE8rYngocu5gEk',
    appId: '1:961998777091:ios:eb9169114e3807be199736',
    messagingSenderId: '961998777091',
    projectId: 'yagsa-9ce79',
    storageBucket: 'yagsa-9ce79.firebasestorage.app',
    iosBundleId: 'com.example.yagsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDablGz5U38nZi-dipLyabGzHhhaE59Cx0',
    appId: '1:961998777091:web:4c714663d374a9b8199736',
    messagingSenderId: '961998777091',
    projectId: 'yagsa-9ce79',
    authDomain: 'yagsa-9ce79.firebaseapp.com',
    storageBucket: 'yagsa-9ce79.firebasestorage.app',
    measurementId: 'G-G9V7TYLP5Y',
  );
}
